# Generated by Django 2.1.7 on 2019-10-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('phone2', models.CharField(max_length=20)),
                ('phone3', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('aadhar', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.CharField(max_length=50)),
                ('profile', models.FileField(blank=True, upload_to='')),
                ('img1', models.FileField(blank=True, upload_to='')),
                ('img2', models.FileField(blank=True, upload_to='')),
                ('img3', models.FileField(blank=True, upload_to='')),
                ('img4', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
