# Generated by Django 2.1.7 on 2019-10-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='phone3',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='profile',
        ),
        migrations.AddField(
            model_name='signup',
            name='dob',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='signup',
            name='profile',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userdata',
            name='comments',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='userdata',
            name='time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='aadhar',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='fullname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='aadhar',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
