# Generated by Django 2.1.7 on 2019-10-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20191020_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='phone2',
            new_name='altphone',
        ),
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='caop',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userdata',
            name='diagnoses',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userdata',
            name='doctorname',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userdata',
            name='hospitalname',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userdata',
            name='immunizationdates',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userdata',
            name='mobileno',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userdata',
            name='prescription',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userdata',
            name='prescription1',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userdata',
            name='prescription2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userdata',
            name='prescription3',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userdata',
            name='progressnotes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userdata',
            name='vitalsigns',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
